{
  "comments": [
    {
      "key": {
        "uuid": "e243d4e6_dddbc94b",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/virtual_machine_interface.py",
        "patchSetId": 11
      },
      "lineNbr": 1450,
      "author": {
        "id": 56
      },
      "writtenOn": "2020-09-23T00:31:19Z",
      "side": 1,
      "message": "We need a try catch here, as uuid_tp_fq_name will raise exception",
      "revId": "5afaed4805ca48cf2b6989b772a8ec991dcb9d68",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}