{
  "comments": [
    {
      "key": {
        "uuid": "043b5106_3ae1f728",
        "filename": "src/config/vnc_openstack/vnc_openstack/neutron_plugin_db.py",
        "patchSetId": 1
      },
      "lineNbr": 4975,
      "author": {
        "id": 64
      },
      "writtenOn": "2020-09-30T03:29:07Z",
      "side": 1,
      "message": "At this point, i suppose \"e\" should have been defined by any one of the try/except block. \nI\u0027d like to reprint the original exception rather than the one we construct. \nTo handled pep8, Could you define \"e\" at the top (at #4940) with the message you defined? so they can get overwritten by original exception?\nAlso could you change \"e\" to any meaningful name or at least \"err\"?",
      "revId": "933fe97aa5ccbdbde9caac4c7694b600ebb6ecf7",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}